### ISSUE TITLE
Referrer problem

### ISSUE THREAD

**Issue by JohnDoez** [ahodesuka/ahoviewer#19]
I'm trying to view image from behoimi.org but none of the images are available and in their forums they said that a problem with sending a blank referrer of bad user strings could cause that. Is it possible to fix this?

Link : http://behoimi.org/forum/show/395

**Comment by ahodesuka** [comment]
Should work now.

**Comment by JohnDoez** [comment]
The changes you made partially worked, it's now possible to see the image on the side pane but when you click on a image a picture of a sausage and the word "NO" is displayed instead.

**Comment by ahodesuka** [comment]
It shows the correct images for me.
The only time I got the sausage image was before I made the change to the referrer.
Are you sure you're using version `1.4.0-4-gefce7a6`?

**Comment by JohnDoez** [comment]
I'll clone the repo when I get home, I tried the AUR package yesterday and it didn't work.

**Comment by JohnDoez** [comment]
Sorry for the huge delay, I cloned the repo and installed the new version but I still get the sausage
![2015-11-10-013907_1024x768_scrot](https://cloud.githubusercontent.com/assets/15521854/11056075/dbf93518-874b-11e5-8882-729132f89541.png)

**Comment by ahodesuka** [comment]
Are you able to view the images on the actual site?
What OS are you using?  What version of curl do you have installed?
Something odd I noticed is that your total posts (584477) does not match when I check behoimi.
Is the site url set to `http://behoimi.org`?

**Comment by JohnDoez** [comment]
I reinstalled everything and deleted the ahoviewer folder in ~/.config and now everything works! Thanks!
